version: '3'
services:
  zookeeper:
    image: bitnami/zookeeper:3.9
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - kafka_net

  kafka:
    image: bitnami/kafka:3.6
    ports:
      - "9092:9092"
    environment:
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://172.20.124.19:9092
      - KAFKA_CFG_LISTENERS=PLAINTEXT://0.0.0.0:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_NUM_PARTITIONS=3
      - KAFKA_CFG_LOG_RETENTION_HOURS=24  # 只保存 24 小时日志
      - KAFKA_CFG_LOG_RETENTION_BYTES=1073741824  # 每个 Topic 限制 1GB
      - KAFKA_CFG_MESSAGE_MAX_BYTES=1048576  # 单条消息最大 1MB
      - KAFKA_CFG_MAX_CONNECTIONS=10  # 限制最大连接数 10
      - KAFKA_CFG_NUM_NETWORK_THREADS=2  # 限制网络线程数
      - KAFKA_CFG_NUM_IO_THREADS=4  # 限制 I/O 线程
      - KAFKA_CFG_FETCH_MAX_BYTES=5242880  # 消费者单次最多拉取 5MB
      - KAFKA_CFG_CONSUMER_MAX_POLL_RECORDS=10  # 消费者单次最多拉取 10 条消息
    depends_on:
      - zookeeper
    networks:
      - kafka_net

networks:
  kafka_net:
    driver: bridge
